name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to test'
        required: true
        default: '1.0.0'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node v${{ secrets.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - run: npm install
      - run: npm run lint

  build:
    name: Build bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.email "${{ github.actor }}"
          git config --global user.name "${{ github.repository_owner }}"
          git checkout -b release/${{ github.event.inputs.version }}

      - name: Test and Build
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - run: |
          npm i -g @vercel/ncc
          npm install --production
          npm run build

      - name: Clean files
        run: |
          rm .gitignore
          rm -Rf node_modules/

      - name: Git Create Branch release/${{ github.event.inputs.version }}
        run: |
          git add .
          git commit -m "Auto commit from Github Actions #${{ github.run_id }}"
          git push origin release/${{ github.event.inputs.version }} -f
          git tag -a v${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }}"

  deploy:
    name: Deploy Bundle
    runs-on: ubuntu-latest
    needs:
      - test
      - build

    steps:
      - name: Set Time
        run: echo "TIME=$(date --rfc-3339=date)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          tag_name: v/${{ github.event.inputs.version }}
          release_name: v${{ github.event.inputs.version }}
          body: |
            Created on ${{ env.TIME }} using automated Workflow by ${{ github.actor }}
          draft: false
          prerelease: false
